### ISSUE TITLE
NullPointerException at AdView.onPrepared

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#1]
following exception raises sometimes:

```
Fatal Exception: java.lang.NullPointerException
       at com.appvador.ads.AdView.onPrepared(AdView.java:377)
       at com.appvador.common.VideoView$2.onPrepared(VideoView.java:334)
       at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:1523)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4441)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

at AppVadorSDK-3.08.jar.

**Comment by najeira** [comment]
This exception appears very frequently.

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
