### ISSUE TITLE
NullPointerException at AdView.replay

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#2]
```
Fatal Exception: java.lang.NullPointerException
       at com.appvador.ads.AdView.replay(AdView.java:363)
       at com.appvador.ads.AdView.access$700(AdView.java:50)
       at com.appvador.ads.AdView$OnReplayListener.onClick(AdView.java:630)
       at android.view.View.performClick(View.java:4504)
       at android.view.View$PerformClick.run(View.java:18539)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5191)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
