### ISSUE TITLE
NullPointerException at AdView.unmute

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#3]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.appvador.ads.vast.VastAd com.appvador.ads.AdConfiguration.getVastAd()' on a null object reference
       at com.appvador.ads.AdView.unmute(AdView.java:344)
       at com.appvador.ads.AdView$OnSoundOnListener.onClick(AdView.java:638)
       at android.view.View.performClick(View.java:4766)
       at android.view.View$PerformClick.run(View.java:19683)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by at-vinhhlb** [comment]
@najeira  I also got same issue, did you resolve it?

**Comment by najeira** [comment]
@at-vinhhlb No. AppVador does not provide new SDK.

I removed AppVador SDK from my Android app.

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
