### ISSUE TITLE
NullPointerException at Appvador.onReadyToPlayAd

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#4]
```
Fatal Exception: java.lang.NullPointerException
       at tv.mixch.service.ads.Appvador.onReadyToPlayAd(Appvador.java:103)
       at com.appvador.ads.AdManager$3.run(AdManager.java:233)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5159)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:815)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:582)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
