### ISSUE TITLE
NullPointerException at AdView.onInView

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#5]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.appvador.ads.vast.VastAd com.appvador.ads.AdConfiguration.getVastAd()' on a null object reference
       at com.appvador.ads.AdView.onInView(AdView.java:324)
       at com.appvador.ads.AdView.access$1000(AdView.java:41)
       at com.appvador.ads.AdView$Runner$1.run(AdView.java:614)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5438)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:917)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
```

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
