### ISSUE TITLE
ArrayIndexOutOfBoundsException at VideoView$ResourceLoaderTask.doInBackground

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#6]
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ArrayIndexOutOfBoundsException: src.length=2048 srcPos=2048 dst.length=2048 dstPos=0 length=2048
       at java.lang.System.arraycopy(System.java:252)
       at com.android.okio.Segment.split(Segment.java:98)
       at com.android.okio.OkBuffer.write(OkBuffer.java:590)
       at com.android.okio.OkBuffer.read(OkBuffer.java:621)
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
       at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
       at java.io.InputStream.read(InputStream.java:162)
       at com.appvador.common.VideoView$ResourceLoaderTask.doInBackground(VideoView.java:600)
       at com.appvador.common.VideoView$ResourceLoaderTask.doInBackground(VideoView.java:552)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
