### ISSUE TITLE
ArrayIndexOutOfBoundsException at VideoView$ResourceLoaderTask.doInBackground

### ISSUE THREAD

**Issue by najeira** [appvador/AppVadorSample-3.0-Android#8]
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.Okio$1.write(Okio.java:65)
       at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
       at com.android.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:56)
       at com.android.okhttp.internal.http.HttpConnection.writeRequest(HttpConnection.java:157)
       at com.android.okhttp.internal.http.HttpTransport.writeRequestHeaders(HttpTransport.java:97)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:599)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:190)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
       at com.appvador.common.VideoView$ResourceLoaderTask.doInBackground(VideoView.java:572)
       at com.appvador.common.VideoView$ResourceLoaderTask.doInBackground(VideoView.java:552)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

**Comment by najeira** [comment]
I think this will not be solved anymore, so I close this.
